[project]
name = "debmagic"
version = "0.1.0"
description = "build debian packages"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-debian>=1.0",
]

[build-system]
requires = ["uv_build>=0.8.0,<0.9.0"]
build-backend = "uv_build"
