[dependency-groups]
dev = [
    { include-group = "docs" },
    "pytest>=9.0.1",
    "pytest-cov>=7.0.0",
    "ruff",
    "pre-commit",
    "ty==0.0.2",
]
docs = [
    "sphinx>=8.2.3,<9",
    "myst-parser>=4.0.1",
    "sphinx-autobuild>=2025.8.25",
    "sphinx-copybutton>=0.5.2",
    "sphinx-rtd-theme>=3.0.2",
]

[tool.uv]
package = false

[tool.uv.sources]
debmagic-common = { workspace = true }
debmagic-pkg = { workspace = true }
debmagic = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]

[tool.ruff]
line-length = 120
target-version = "py312"
extend-exclude = [
    ".idea",
    ".mypy_cache",
    ".venv*",
    "docs",
    "debian",
    "__pycache__",
    "*.egg_info",
]

[tool.ruff.lint]
select = ["E", "W", "F", "I", "C", "N", "PL", "RUF", "I001"]
ignore = ["E722", "PLR2004", "PLR0912", "PLR5501", "PLC0415", "PLR0911"]
mccabe.max-complexity = 25
pylint.max-args = 10

[tool.pytest]
testpaths = ["tests"]
addopts = ["--ignore=tests/integration/packages"]
