[package]
name = "debmagic"
version = "0.0.1-alpha1"
documentation = "https://debmagic.readthedocs.org"
homepage = "https://github.com/SFTtech/debmagic"
repository = "https://github.com/SFTtech/debmagic.git"
rust-version.workspace = true
edition.workspace = true

[dependencies]
debmagic-common = { workspace = true }
clap = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
config = { workspace = true, features = ["toml"] }
dirs = { workspace = true }
glob = { workspace = true }
libc = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
debian-changelog = { workspace = true }
ignore = { workspace = true }
