[build-system]
requires = ['maturin>=1.9.4,<2']
build-backend = 'maturin'

[project]
name = "debmagic"
version = "0.0.1-alpha.1"
description = "build debian packages"
license = "GPL-2.0-or-later"
# license-files = ["../../LICENSE"]
# readme = "../../README.md"
requires-python = ">=3.12"
classifiers = ["Programming Language :: Python :: 3"]

[project.urls]
homepage = "https://github.com/SFTtech/debmagic"
source = "https://github.com/SFTtech/debmagic.git"
issues = "https://github.com/SFTtech/debmagic/issues"
releasenotes = "https://github.com/SFTtech/debmagic/-/blob/main/debian/changelog"

[tool.maturin]
bindings = "bin"
manifest-path = "Cargo.toml"
module-name = "debmagic.cli"
strip = true
exclude = []
