[project]
name = "debmagic"
version = "0.0.1-alpha.1"
description = "build debian packages"
license = "GPL-2.0-or-later"
# license-files = ["../../LICENSE"]
# readme = "../../README.md"
requires-python = ">=3.12"
classifiers = ["Programming Language :: Python :: 3"]
dependencies = ["debmagic-common", "pydantic>=2,<3"]

[project.urls]
homepage = "https://github.com/SFTtech/debmagic"
source = "https://github.com/SFTtech/debmagic.git"
issues = "https://github.com/SFTtech/debmagic/issues"
releasenotes = "https://github.com/SFTtech/debmagic/-/blob/main/debian/changelog"

[build-system]
requires = ["setuptools>=77.0.0", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project.scripts]
debmagic = "debmagic.cli:main"
